kind: ConfigMap 
apiVersion: v1 
metadata:
  name: uptime-flyway-cm
  namespace: uptime
  labels:
    name: uptime-flyway-cm
    app: uptime
data:
  {{- (.Files.Glob "migration/*.sql").AsConfig | nindent 2 }}
