apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: uptime 
    name: uptime
  name: uptime
  namespace: uptime
  selfLink: /api/v1/namespaces/uptime/services/uptime
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    app: uptime
    name: uptime
  sessionAffinity: None
  type: NodePort
